spring:
  application:
    name: AvisBackend

  # 1. Conexi贸n a Supabase (Reactiva)
  r2dbc:
    url: r2dbc:postgresql://db.shmutxsmjokamnxrkufe.supabase.co:5432/postgres
    username: postgres
    password: AleAdriRober

  # 2. Configuraci贸n de RabbitMQ (Local en Lubuntu)
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  # 3. Configuraci贸n de Redis (Para Subastas / Locks)
  data:
    redis:
      host: localhost
      port: 6379

  # 4. Configuraci贸n del Servidor y RSocket (Para Tailscale)
  rsocket:
    server:
      port: 7000
      transport: tcp
      address: 0.0.0.0

server:
  port: 8080
  address: 0.0.0.0

# 5. APIs Externas
api:
  weather:
    url: "https://api.openweathermap.org/data/2.5"
    key: "0f3fe973a050b2df639fab82f3c33ca6"
  unsplash:
    url: "https://api.unsplash.com"
    key: "LMN6wkrs9pnlyoE29fZVTVqLmfJD6UwU7p1384OUw0E"
  nuthatch:
    url: "https://nuthatch.lastelm.software"
    key: "2ad0ea65-505a-4102-a804-d1a4f72406b8"

# 6. Seguridad JWT
jwt:
  secret: "UnaClaveSecretaMuyLargaYComplejaParaFirmarLosTokensDeAvis2026"
  expiration: 86400000
